name: Deploy Backend to Hugging Face

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Deploy
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        HF_USERNAME: ${{ secrets.HF_USERNAME }}
        HF_SPACE_NAME: ${{ secrets.HF_SPACE_NAME }}
      run: |
        git config --global user.email "bot@github.com"
        git config --global user.name "Bot"

        git clone https://huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME hf

        cp backend/main.py hf/
        cp backend/pyproject.toml hf/
        cp backend/uv.lock hf/
        cp backend/Dockerfile hf/
        cp backend/README.md hf/

        cd hf
        git add .
        git commit -m "Deploy" || echo "No changes"
        git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME main